services:
  lanzou-parser:
    image: ghcr.io/keithw0726/lanzou-url-parser:latest
    container_name: lanzou-url-parser
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=Asia/Shanghai
