services:
  lanzou-parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lanzou-url-parser

    ports:
      - "3000:3000" # 将容器内的 3000 端口映射到宿主机的 3000 端口
    restart: unless-stopped

    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=Asia/Shanghai
